### ISSUE TITLE
Better solution for graphviz executable

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/graphviz-feedstock#34]
Currently the `graphviz.exe` file is installed in `Library\bin\graphviz`. This causes some complications when people want to call the executable as that is not added to the path. Currently we address that by [creating a batch script]( https://github.com/conda-forge/graphviz-feedstock/blob/56f42d20d0c9337ddf34f1ebe113aad48f823891/recipe/bld.bat#L33-L39 ) in `Library\bin`, which calls the executable in `Library\bin\graphviz`. This causes issues downstream where we have needed to extra work to call the batch script. Am wondering if there is a better way for us to address this, which would result in less downstream pain.

xref: https://github.com/conda-forge/python-graphviz-feedstock/pull/6
xref: https://github.com/ContinuumIO/anaconda-issues/issues/1666

**Comment by jakirkham** [comment]
Just to propose a solution here, would it be possible to add a hard link to executables in `Library\bin\graphviz` to `Library\bin` or are there challenges with this approach?

**Comment by jakirkham** [comment]
@ccordoba12, as you are pretty familiar with this problem, do you have any thoughts on this?

**Comment by ccordoba12** [comment]
The right solution would be to compile Graphviz on Windows, but that seems pretty hard.

The problem with the current approach is that the Graphviz installer that we're repackaging as a conda package comes with a lot of third-party libraries (like Qt4 and zlib), so we need to put its contents on `Library\bin\graphviz` instead of `Library\bin`.

So I think the batch script approach is the right one for now (I can't think of a better one). We just need to submit patches to the upstream projects that depend on Graphviz to make them work with batch scripts. That's usually a matter of adding `shell=True` to the `subprocess.call` command that calls Graphviz executables.

**Comment by ankostis** [comment]
I discovered a tough limitation with BAT files: they don't work with UNC `cwd`.
Should i open a new issue?

**Comment by ccordoba12** [comment]
No, thanks.

**Comment by ankostis** [comment]
Note that `python-graphviz-8.4` has does not suffer from UNC problems because it does not set `cwd` to the parent of the filepath.

**Comment by jakirkham** [comment]
So that sounds like a `python-graphviz` issue and not a `graphviz` issue. Could you please raise on that feedstock?

**Comment by ankostis** [comment]
Ok, reported it in conda-forge/python-graphviz-feedstock#32 as advised.

I wanted to cast here my -1 vote against batch proxies for the forthcoming 2.40 release.

**Comment by Nodd** [comment]
sphinx doesn't generate inheritance graphs, if I understand correctly it's because it doesn't support the batch script. Adding `Library\bin\graphviz` to the path does the trick even if not recommended.

**Comment by jakirkham** [comment]
Well there was a recent release of Graphviz if someone wants to tackle upgrading ( https://github.com/conda-forge/graphviz-feedstock/issues/46 ) and building from source on Windows ( https://github.com/conda-forge/graphviz-feedstock/issues/11 ).

**Comment by jakirkham** [comment]
We are now building from source on Windows with PR ( https://github.com/conda-forge/graphviz-feedstock/pull/59 ) 😀
