### ISSUE TITLE
Why is this skipped on windows now?

### ISSUE THREAD

**Issue by scopatz** [conda-forge/graphviz-feedstock#47]
@CJ-Wright - It seems like this is skipped now

**Comment by CJ-Wright** [comment]
I'm not certain why that change was made (despite me making it). Feel free to add it back. (I presume that that version had issues building for windows, but I can't be certain).

**Comment by jakirkham** [comment]
I think we rely on Graphviz to build Windows binaries for us, which we repackage. While they built one for 2.38.0, I don't believe they built one for 2.40.1. Since building from source on Windows has been non-trivial, I think we came to a consensus to push out 2.40.1 for the platforms that support it (skipping Windows).

At this point, I think we would need to build Graphviz from source on Windows. Though they did add CMake support ( https://github.com/conda-forge/graphviz-feedstock/issues/11 ), which should make it easier (if someone is wanting to pursue that 😉)

**Comment by magjac** [comment]
Yes, and we are continuing to improve the build process. See e.g. https://gitlab.com/graphviz/graphviz/-/merge_requests/1529.

**Comment by h-vetinari** [comment]
Was surprised that this is not building for windows anymore when I casually came across the recipe.

Might give it a shot to build it if I find some time...

**Comment by jakirkham** [comment]
Now building from source(!) on Windows with PR ( https://github.com/conda-forge/graphviz-feedstock/pull/59 )
